name: Release

on:
  push:
    tags:
      - "v*"
      - "test-v*"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEBIAN_CODENAME: trixie
  DEBIAN_VERSION: "13"
  DOCKER_VERSION: "29.2.1"
  NERDCTL_VERSION: "2.2.1"
  FLANNEL_VERSION: "1.9.0-flannel1"
  FLANNEL_MINI_VERSION: "1.9.0"
  BINFMT_VERSION: "deploy/v7.0.0-28"
  BINFMT_QEMU_VERSION: "7.0.0"

jobs:
  release:
    strategy:
      max-parallel: 2
      fail-fast: true
      matrix:
        arch: [x86_64, aarch64]
        runtime: [none, docker, containerd, incus]
        include:
          - arch: x86_64
            os: ubuntu-latest
          - arch: aarch64
            os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    name: release-${{ matrix.runtime }}-${{ matrix.arch }}
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Build
        run: |
          make qcow OS_ARCH=${{ matrix.arch }} \
            DEBIAN_CODENAME="${DEBIAN_CODENAME}" \
            DEBIAN_VERSION="${DEBIAN_VERSION}" \
            DOCKER_VERSION="${DOCKER_VERSION}" \
            BINFMT_VERSION="${BINFMT_VERSION}" \
            BINFMT_QEMU_VERSION="${BINFMT_QEMU_VERSION}" \
            RUNTIME=${{ matrix.runtime }}
          ls -lah dist/img

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: img-${{ matrix.arch }}-${{ matrix.runtime }}
          path: dist/img/*-${{ matrix.runtime }}.*
          overwrite: true
          retention-days: 1

  create-release:
    runs-on: ubuntu-latest
    needs: [release]
    if: github.event_name != 'pull_request'
    permissions:
      contents: write
      actions: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false

      - uses: actions/download-artifact@v4
        with:
          path: dist/img

      - name: Create release
        run: >
          tag="${GITHUB_REF##*/}"

          gh release create "${tag}" --draft --title "${tag}" dist/img/*/*.qcow2 dist/img/*/*.sha512sum

      - name: Purge workflow artifacts
        if: always()
        run: |
          gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts \
            --jq '.artifacts[].id' | xargs -r -I {} gh api -X DELETE repos/${{ github.repository }}/actions/artifacts/{}
